### ISSUE TITLE
Update questions developer documentations questsions.yaml

### ISSUE THREAD

**Issue by jeroen1602** [truecharts/website#125]
### Is your feature request related to a problem?

The `manual/development/questions-yaml` file doesn't describe all possible schema types in the `Question Variable Reference` table.

### Describe the solution you'd like

Looking at the code that truenas uses to validate a chart (https://github.com/truenas/catalog_validation/blob/master/catalog_validation/schema/schema_gen.py) it seems that the `uri` type is missing from the documentation.

### Describe alternatives you've considered

Does not apply

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
To be honest we should completely remove this.
We're not in the bussiness of documenting an upstream and we cannot even keep this updated anyway

**Comment by jeroen1602** [comment]
You are right that it isn't the job of this project to document how to create a chart. It is however very useful since trueNAS doesn't seem to publish any documentation on how to do so.

**Comment by Ornias1993** [comment]
> You are right that it isn't the job of this project to document how to create a chart. It is however very useful since trueNAS doesn't seem to publish any documentation on how to do so.

To be frank: TrueNAS Doesn't publish ANY developer documentation at all. Besides mightbe 1 or 2 build instructions.

**Comment by stavros-k** [comment]
You can keep an eye there `https://github.com/truenas/charts/pull/998` which at some point will include more docs.
Just a bit tight on time currently.

**Comment by stavros-k** [comment]
Given that the questions.yaml is something very platform specific and also the above mentioned PR is merged. 
There are some basic docs on how things work. If still more info needed, might be best to file tickets upstream, so the actual creators of the questions system can answer those accurately.
Thanks
