### ISSUE TITLE
Gh action recreates the old description page

### ISSUE THREAD

**Issue by xstar97** [truecharts/website#132]
### Is your feature request related to a problem?

The awesome mdx react page isn't able to be viewed or accessible due to a gh action or other recreating the old page with the same name. 

### Describe the solution you'd like

Stop the automation from recreating the old file

### Describe alternatives you've considered

Complain.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
thx

**Comment by Ornias1993** [comment]
Fixed & fix deploying.
