### ISSUE TITLE
Improve "Helm" and "Rancher" sections of the documentation

### ISSUE THREAD

**Issue by robotcorner** [truecharts/website#220]
### Is your feature request related to a problem?

I would like to know more about the future plans for rancher and helm. Is there a potential setup outside of using TrueNAS SCALE that the authors know more about?

### Describe the solution you'd like

I would like some additional information in these sections. If there was more documentation and it was more clear how to get started with either one of these sections that would be awesome. For example, I know that generally only TrueNAS SCALE has been supported, but it would be great to know if there's a system already mostly in place to run a similar system with a rancher GUI and truecharts as the backbone.

### Describe alternatives you've considered

The alternative is being an expert on a codebase because no one knows that code or strategies better than the maintainers.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
We don't take github issues for documentation. It's a "feel free to fix it yourself" section of the project.

On topic:
- As stated in the news articles there is not official Rancher support at this time.
- Helm support is "like normal", we're not likely to offer much step-by-step advice on it, as we need to assume the users knows how to use helm.

**Comment by robotcorner** [comment]
So is there a rough timeline on rancher? 

I get the strategy is fix it yourself with some of these things. However, the effective rate a maintainer could enhance the documentation is way way quicker. I just thought the sections needed a little love is all and the idea that the general user is going to write the documentation doesn't make a lot of sense if you think about it. 

Also now that we can't suggest these thinks in github to track then (idk what the point of a feature request on it is) and we can't suggest new apps on github anymore how do these types of request get properly tracked and supported eventually. Just because I'm the first one to voice something doesn't mean I'm the only person thinking it and if there was at least a place for the community to track these kind of nice to have request and app feature suggestions then that would be nice because the one platform we used to track these things in (github) you don't want requests in. Discord is a messaging system and is not sufficient for tracking such work through inception to completion (at least for app work and requests), we need a tacking sheet or something if were not using github for that kind of stuff.

**Comment by Ornias1993** [comment]
Simply put: chart request where just a garbage dump that never got any maintainer attention, because we never intended for it to get any.

there where flooding the github with issues that only existed to give people a place to dump them into.

**Comment by Ornias1993** [comment]
Im leaving this issue, but considering how much this is derailling ill lock it.
