### ISSUE TITLE
Github issue form for documentation

### ISSUE THREAD

**Issue by hboyd2003** [truecharts/website#303]
### Is your feature request related to a problem?

When submitting an issue your only choices for issue forms are 

- "⚙️ Bug Report 🪛"
- "⚙️ Feature or Enhancement Request 🙏"
- "⚙️ Report Outdated App 🪛".

 None of which are usable for issues relating to documentation.

### Describe the solution you'd like

A issue form for documentation

### Describe alternatives you've considered

- Submitting the issue with the form then just editing the issue to remove un-needed stuff.
- Placing n/a for most questions on the existing issue form

### Additional context

While it appears that there are not many issues relating to documentation, a form should exist to people do not shy away from reporting it since there is no correct option for reporting it.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
We don't take documentation issues on github anyway, as there are literally thousands of points to work on and we don't aim on tracking them all.
