### ISSUE TITLE
Tripple negative in Documentaion

### ISSUE THREAD

**Issue by publicarray** [truecharts/website#339]
### Is your feature request related to a problem?

I don't understand this sentence:

>Do NOT hit the Stop Button UNLESS you are certain the App does not use [CloudNativePG (CNPG)](https://cloudnative-pg.io/).

https://truecharts.org/manual/FAQ

So you can hit the stop except if CloudNativePG is used?
So you should not hit the stop if CloudNativePG is used?

### Describe the solution you'd like

Remove the 3 negatives in the sentence. Maybe separate it into 2 sentences.

### Describe alternatives you've considered

Ignore it

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Sorry, we don't take docs issues for all the 99999999 different small issues with them, it's a wiki feel feel to PR any changes you feel are needed.

**Comment by publicarray** [comment]
I would have created a PR if I understood what the author was saying. I don't want to submit a PR where I could say the opposite of what the author intended.
