### ISSUE TITLE
definitions on categories

### ISSUE THREAD

**Issue by icf20** [truecharts/website#380]
### Is your feature request related to a problem?

![imagen](https://github.com/truecharts/website/assets/17784575/21d13ec8-c96a-42ee-a66d-225ab4fb618c)

what do this words mean

### Describe the solution you'd like

define the categories do understand what is what

### Describe alternatives you've considered

mind reading but failed

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Trains aren't catagories.

How ever, we don't take documentation issues on github, otherwise we would flood things with 999999 different small tidbits. Unless it's things we as maintainers have a personal todo on.

Feel free to PR or bust, basically.

**Comment by icf20** [comment]
https://github.com/truecharts/website/ is the website or not?


> Feel free to PR or bust, basically.

so add what? i cant mind read to explain what do you mean by "Operators, Unstable, Stable, Enterprise, Incubator, dependency

**Comment by Ornias1993** [comment]
> https://github.com/truecharts/website/ is the website or not?

Correct, and we do not take documentation or website issues as a project. Sorry.

> > Feel free to PR or bust, basically.
> 
> so add what? i cant mind read to explain what do you mean by "Operators, Unstable, Stable, Enterprise, Incubator, dependency

Afaik it's documented somewhere in the docs.
But we do not have the time to help-out as maintainers on this, as our todo list is full.

Feel free to join the discord or PR a fix yourself.
