### ISSUE TITLE
Inconsistent hyperlinks for charts

### ISSUE THREAD

**Issue by Kimi450** [truecharts/website#460]
### App Name

Website

### Operating System

Other Using Helm (please specify)

### App Version

NA

### Application Events

```Shell
NA
```

### Application Logs

```Shell
NA
```

### Application Configuration

NA

### Describe the bug

When you click on at least some (if not most) the links in the [Chart List](https://truecharts.org/charts/description_list/), they seem to default to the `incubator` URI (which is incorrect). They need to go to the correct chart homepage

### To Reproduce

1. Go to https://truecharts.org/charts/description_list/
2. Click on some random charts ([acestream](https://truecharts.org/charts/incubator/acestream) for `stable`)
3. Youll see it links to incubator instead of stable

### Expected Behavior

Linking to the correct "type" of chart

### Screenshots

NA

### Additional Context

NA

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Descriptionlist is known broken and not maintained at the moment.
We saidly enough don't take reports for linking issues anyway.

**Comment by Kimi450** [comment]
> Descriptionlist is known broken and not maintained at the moment.
> We saidly enough don't take reports for linking issues anyway.

I suggest keeping this issue open for any volunteers to pick it up and work on it

**Comment by Ornias1993** [comment]
> > Descriptionlist is known broken and not maintained at the moment.
> > We saidly enough don't take reports for linking issues anyway.
> 
> I suggest keeping this issue open for any volunteers to pick it up and work on it

No we do not.
First off: fixing description list is something only maintainers can do
But second: we don't take hyperlink issues at all, otherwise we will flood the issues tracker with literally hunderds of reports.
