### ISSUE TITLE
Quickstart links to 404

### ISSUE THREAD

**Issue by b-m-f** [truecharts/website#51]
### App Name

XXX

### SCALE Version

22.02.3

### App Version

XXX

### Application Events

```Shell
https://truecharts.org/docs/manual/SCALE%20Apps/Quick-Start%20Guides/Installing-an-App

Leads to 404
```

### Application Logs

```Shell
XXX
```

### Application Configuration

XXX

### Describe the bug

Wrong internal link on website

### To Reproduce

go to https://truecharts.org/docs/charts/dependency/collabora-online/
click "To install this Chart on TrueNAS SCALE check our [Quick-Start Guide](https://truecharts.org/docs/manual/SCALE%20Apps/Quick-Start%20Guides/Installing-an-App)."

It breaks

### Expected Behavior

Should show the quickstart guide

### Screenshots

XXX

### Additional Context

I like turtles

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
As explained to you in your PR, this issue is not managed on this Repo.
