### ISSUE TITLE
getting-started (https://truecharts.org/manual/SCALE/guides/getting-started/) is missing

### ISSUE THREAD

**Issue by Andrysky** [truecharts/website#596]
### chart Name

-

### Operating System

TrueNAS SCALE 23.10.2

### Deployment Method

TrueNAS SCALE charts

### Chart Version

-

### Kubernetes Events

```Shell
-
```

### chartlication Logs

```Shell
-
```

### Chart Configuration

-

### Describe the bug

Hello, where did the getting-started guide go? address https://truecharts.org/manual/SCALE/guides/getting-started/ empty

### To Reproduce

goto https://truecharts.org/manual/SCALE/guides/getting-started/

### Expected Behavior

guide exist

### Screenshots

-

### Additional Context

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] I've prefixed my issue title with `[Chart-Name]`

**Comment by stavros-k** [comment]
due to new website a lot of links changed location. use the menu or search ( might take some time for search to index everyhting)

**Comment by Andrysky** [comment]
I think I found it https://truecharts.org/platforms/scale/guides/getting-started/
