### ISSUE TITLE
[docs] Google SEO main hyperlink to Scale Docs - link broken

### ISSUE THREAD

**Issue by sanerspace** [truecharts/website#602]
### chart Name

none

### Operating System

TrueNAS SCALE 23.10.2

### Deployment Method

TrueNAS SCALE charts

### Chart Version

0.0

### Kubernetes Events

```Shell
n/a
```

### chartlication Logs

```Shell
n/a
```

### Chart Configuration

n/a

### Describe the bug

When clicking the link that Google provides to https://truecharts.org/manual/SCALE/guides/getting-started/
Then a soft 404 error occurs on the website. The page literally says "Lost in the Docs?"

### To Reproduce

1. Google Truecharts docs
2. Click https://truecharts.org/manual/SCALE/guides/getting-started/

### Expected Behavior

To arrive at the landing page for TrueCharts Scale Getting Started

### Screenshots

is obvious

### Additional Context

If the problem is with Google SEO needing to re-learn the landing page, I am fine with that. Just didn't know if this link was intentionally changed on the TrueCharts website.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] I've prefixed my issue title with `[Chart-Name]`

**Comment by Ornias1993** [comment]
There is nothing we can do about this, besides submitting the new sitemap.
