### ISSUE TITLE
Eample misspelled

### ISSUE THREAD

**Issue by 7777vito** [truecharts/website#782]
### chart Name

main

### Operating System

other

### Deployment Method

Helm

### Chart Version

none

### Kubernetes Events

```Shell
none
```

### chartlication Logs

```Shell
none
```

### Chart Configuration

none

### Describe the bug

none

### To Reproduce

1.Go to https://truecharts.org/common/ingress/#hostspathsoverrideserviceport

### Expected Behavior

none

### Screenshots

![image](https://github.com/user-attachments/assets/6ea5f2cf-1e0c-408f-bbb3-f47edfa6591f)

### Additional Context

website\src\content\docs\common\ingress\index.md:476

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] I've understand TrueNAS SCALE Apps are deprecated and TrueCharts does not accept TrueNAS SCALE related issues
- [X] I've prefixed my issue title with `[Chart-Name]`

**Comment by stavros-k** [comment]
Fixed in 40d753637dc20a9a01983259cbe3c8c67315ccdc
