### ISSUE TITLE
Charts List refers to nonexistent Chart root index

### ISSUE THREAD

**Issue by HumbleDeer** [truecharts/website#80]
### Regarding

TrueCharts Docs

### Describe the bug

The Charts List (https://truecharts.org/docs/charts/description_list) links to charts by their root directory (e.g. https://truecharts.org/docs/charts/stable/syslog-ng/). There is possibly no index in this directory, and the only file may be the auto-generated changelog. This results in a 404

### To Reproduce

Visit https://truecharts.org/docs/charts/description_list

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
I'm going to close this, as this is a very well-known consequence of the just-finished CI rework.
We're aware this is sub optimal, but these big reworks take time.

**Comment by HumbleDeer** [comment]
Is there anywhere I can keep track of any progress regarding these
consequences? I don't see any planning on GitHub

**Comment by Ornias1993** [comment]
Nope.
