### ISSUE TITLE
[bug] Individual reference pages are missing

### ISSUE THREAD

**Issue by joe733** [truecharts/website#81]
### App Name

Any

### SCALE Version

22.02.3

### App Version

Any

### Application Events

```Shell
NA
```

### Application Logs

```Shell
NA
```

### Application Configuration

NA

### Describe the bug

Pages to individual charts are missing,  few examples:

- https://truecharts.org/docs/charts/stable/actualserver/
- https://truecharts.org/docs/charts/incubator/kdenlive/
- https://truecharts.org/docs/charts/incubator/searx/
- 

### To Reproduce

1. Go to any of the chart page from https://truecharts.org/docs/charts/description_list
2. And you see "Page Not Found"

### Expected Behavior

Chart pages are not 404.

### Screenshots

![image](https://user-images.githubusercontent.com/38415384/201800791-9f361f40-93cf-4240-bfa6-afcc36618ef1.png)

### Additional Context

> Unrelated, but the issue form template isn't well suited for Trucharts website repo.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Duplicate.
Please check other issues first.

**Comment by joe733** [comment]
Oh gotcha, #80 seemed addressing a different issue.

I think this is the CI https://github.com/truecharts/website/actions.

> I'm going to close this, as this is a very well-known consequence of the just-finished CI rework.
We're aware this is sub optimal, but these big reworks take time. ref: https://github.com/truecharts/website/issues/80#issuecomment-1314107629

If so, is it really a good idea to build it every hour? The pages are down, as of writing this comment.

**Comment by Ornias1993** [comment]
Not relevant to this issue…
