### ISSUE TITLE
Truecharts.org chart documentation base URLs are broken.

### ISSUE THREAD

**Issue by tyvsmith** [truecharts/website#87]
### App Name

All

### SCALE Version

22.02.4

### App Version

N/a

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

N/A

### Describe the bug

Links from the github docs to base URL for charts are broken and end up in Page Not Found. Many search indexers are picking these up.

Examples:

- https://github.com/truecharts/charts/tree/master/charts/stable/k8s-gateway Links to https://truecharts.org/docs/charts/stable/k8s-gateway/ (broken)
 - https://github.com/truecharts/charts/tree/master/charts/stable/radarr Links to https://truecharts.org/docs/charts/stable/radarr/ (broken)
- https://github.com/truecharts/charts/tree/master/charts/stable/nextcloud links to https://truecharts.org/docs/charts/stable/nextcloud/ (broken)

### To Reproduce

Go to https://github.com/truecharts/charts/tree/master/charts/stable/radarr (or any github URL) and click the URL to the docs, note the bad url.

### Expected Behavior

Urls are valid

### Screenshots

![image](https://user-images.githubusercontent.com/309657/202918053-e9572b1e-68fc-4aa4-bbe2-8c36b393e711.png)

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
It would be really amazing if people check for duplicates before filing issues
